name: Node CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Install and Build 🔧
      run: |
        npm install
        npm run build
      env:
        CI: true

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.5.9
      with:
        ACCESS_TOKEN: ${{ secrets.GHTOKEN }}  
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: dist
        CLEAN: true
        SSH: false
